baseurl = "https://mdneuzerling.com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
languageCode = "en"
defaultContentLanguage = "en"
title = "Hugo Theme Dream"
theme = "hugo-theme-dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "David Neuzerling"
  # description = ""
  avatar = "/img/profile/profile_1_small.png"
  motto = "Data, maths, R"
  
  # email = "g1enyy0ung@gmail.com"
  github = "mdneuzerling"
  twitter = "mdneuzerling"
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  # siteStartYear = 2016

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404Button = true
